"""Authority separation for the OKF/profile observation (M004-S02/S04).

The observation surface must be import-isolated and causally inert: no native
authority module may import it, reference it, or branch on its results, and
changing an artifact's OKF/profile outcome while holding its native content
constant must change no native result — prompt/report/verdict validity,
accepted-slice discovery, the planning frontier, the human gate, the step
actor, runner authorization, write permission, handoff rendering, the journal,
or generated bytes. This file proves the separation structurally (AST over
every product module) and behaviorally (mutation-style project matrices).
Fixture-corpus parity and the limit matrix live in
``test_okf_profile_fixture_parity.py``.
"""

from __future__ import annotations

import ast
import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import frutlups
import frutlups.okf_profile
from frutlups.handoff import build_coder_handoff, build_reviewer_handoff
from frutlups.journal import JOURNAL_REL_PATH
from frutlups.okf_profile import OKFProfileObservation, observe_okf_profile_path
from frutlups.review_report import parse_review_report_verdict_text

from test_orchestrator import _make_template
from test_resumable_status import (
    _minimal_coding_prompt,
    _minimal_self_report,
    _run,
    _write_active_roadmap,
    _write_coding_prompt,
    _write_detailed_roadmap,
    _write_review_prompt,
    _write_review_report,
    _write_self_report,
    _write_verdict_record,
)
from test_workflow_metadata_regions import _meta_text

_SRC_ROOT = Path(frutlups.__file__).resolve().parent

# The only product modules allowed to know the observation surface exists.
_ALLOWED_IMPORTERS = {"okf_profile.py", "__init__.py"}

_FIVE_PUBLIC_NAMES = (
    "OKF_PROFILE_OBSERVATION_CONTRACT_ID",
    "OKF_PROFILE_OBSERVATION_CONTRACT_VERSION",
    "OKFProfileObservation",
    "ProfileLayerResult",
    "observe_okf_profile_path",
)

# Every native authority module named by the accepted separation contract, plus
# the remaining product modules; the guard below scans all of them, and this
# list documents the modules whose isolation is contractual.
_AUTHORITY_MODULES = (
    "project.py",
    "orchestrator.py",
    "gate.py",
    "handoff.py",
    "journal.py",
    "layout.py",
    "cli.py",
    "prompts.py",
    "prompt_template.py",
    "review_prompt_template.py",
    "review_report.py",
    "self_report.py",
    "state.py",
    "artifacts.py",
    "_scaffold.py",
)


def _product_modules() -> list[Path]:
    return sorted(_SRC_ROOT.glob("*.py"))


class ObservationImportGuardTests(unittest.TestCase):
    def test_authority_module_list_is_current(self) -> None:
        names = {path.name for path in _product_modules()}
        missing = set(_AUTHORITY_MODULES) - names
        self.assertFalse(missing, f"contractual modules disappeared: {sorted(missing)}")

    def test_only_the_package_root_imports_the_observation_module(self) -> None:
        for module_path in _product_modules():
            if module_path.name in _ALLOWED_IMPORTERS:
                continue
            tree = ast.parse(module_path.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        self.assertNotIn(
                            "okf_profile",
                            alias.name,
                            f"{module_path.name} imports the observation module",
                        )
                elif isinstance(node, ast.ImportFrom):
                    module = node.module or ""
                    self.assertNotIn(
                        "okf_profile",
                        module,
                        f"{module_path.name} imports from the observation module",
                    )
                    for alias in node.names:
                        self.assertNotIn(
                            alias.name,
                            _FIVE_PUBLIC_NAMES,
                            f"{module_path.name} imports an observation name",
                        )

    def test_no_authority_module_references_the_observation_surface(self) -> None:
        # Stricter than the import scan: no identifier or attribute anywhere in
        # a non-allowed product module may name the observation module or any
        # of its five public names, so indirect access (getattr, frutlups.X)
        # is caught as well.
        watched = set(_FIVE_PUBLIC_NAMES) | {"okf_profile"}
        for module_path in _product_modules():
            if module_path.name in _ALLOWED_IMPORTERS:
                continue
            tree = ast.parse(module_path.read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if isinstance(node, ast.Name) and node.id in watched:
                    self.fail(f"{module_path.name} references {node.id}")
                if isinstance(node, ast.Attribute) and node.attr in watched:
                    self.fail(f"{module_path.name} references .{node.attr}")
                if isinstance(node, ast.Constant) and isinstance(node.value, str):
                    if node.value in _FIVE_PUBLIC_NAMES or node.value == "okf_profile":
                        self.fail(
                            f"{module_path.name} carries the literal {node.value!r}"
                        )

    def test_the_observation_module_imports_no_authority_module(self) -> None:
        # Separation is two-way: the observation must not read native state
        # either. Its only product import is the accepted YAML boundary.
        tree = ast.parse((_SRC_ROOT / "okf_profile.py").read_text(encoding="utf-8"))
        imported: set[str] = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom):
                imported.add(node.module or "")
        frutlups_imports = {name for name in imported if name.startswith("frutlups")}
        self.assertEqual(frutlups_imports, {"frutlups._yaml"})

    def test_the_yaml_boundary_does_not_know_the_observation_exists(self) -> None:
        source = (_SRC_ROOT / "_yaml.py").read_text(encoding="utf-8")
        self.assertNotIn("okf_profile", source)
        for name in _FIVE_PUBLIC_NAMES:
            self.assertNotIn(name, source)


# ---------------------------------------------------------------------------
# Behavioral separation: profile mutations move no native result (S04)
# ---------------------------------------------------------------------------

# Concept-frontmatter variants that move ONLY the OKF/profile observation.
# Each is a well-formed frame (native region facts stay constant); `{kind}`
# is the artifact's registry type.
_PROFILE_VARIANTS: dict[str, str] = {
    "legacy": "",
    "profile_valid": '---\ntype: {kind}\nframework_profile: "0.1-rc.1"\n---\n',
    "profile_version_invalid": '---\ntype: {kind}\nframework_profile: "9.9"\n---\n',
    "profile_type_invalid": '---\ntype: made_up\nframework_profile: "0.1-rc.1"\n---\n',
    "profile_subset_invalid": (
        '---\ntype: {kind}\nframework_profile: "0.1-rc.1"\ntags: [a, b]\n---\n'
    ),
}

_VARIANT_ROWS: dict[str, tuple[str, str | None, str, str | None]] = {
    "legacy": ("not_evaluated", None, "not_applicable", None),
    "profile_valid": ("pass", None, "pass", None),
    "profile_version_invalid": ("pass", None, "fail", "PROFILE_VERSION_UNSUPPORTED"),
    "profile_type_invalid": ("pass", None, "fail", "PROFILE_TYPE_UNSUPPORTED"),
    "profile_subset_invalid": ("pass", None, "fail", "PROFILE_YAML_OUT_OF_SUBSET"),
}

_FENCED_ROUTING_BODY = (
    "# Coding Prompt 012: Something\n\n"
    "Front matter:\n\n"
    "```yaml\n"
    "milestone: M004\n"
    "slice: M004-S01\n"
    "title: Something\n"
    "```\n\n"
    "## Body\n\nText.\n"
)

_FIXTURES = Path(__file__).resolve().parent / "fixtures" / "template_v3_driver_contract"


def _layers(observation: OKFProfileObservation) -> tuple[str, str | None, str, str | None]:
    return (
        observation.okf_concept.result,
        observation.okf_concept.reason,
        observation.framework_profile.result,
        observation.framework_profile.reason,
    )


def _observe_text(text: str) -> tuple[str, str | None, str, str | None]:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "artifact.md"
        path.write_text(text, encoding="utf-8", newline="\n")
        return _layers(observe_okf_profile_path(path))


class PromptValidityMutationTests(unittest.TestCase):
    def test_profile_variants_move_the_observation_but_never_prompt_routing(self) -> None:
        native_results = set()
        observations = set()
        for label, frame in _PROFILE_VARIANTS.items():
            with self.subTest(variant=label):
                text = frame.format(kind="coding_prompt") + _FENCED_ROUTING_BODY
                meta = _meta_text(text)
                native_results.add(
                    (meta.milestone_id, meta.slice_id, tuple(meta.errors))
                )
                observations.add(_observe_text(text))
                self.assertEqual(_observe_text(text), _VARIANT_ROWS[label])
        # One native answer across all five variants; five distinct
        # observations. The observation moved; routing did not.
        self.assertEqual(len(native_results), 1)
        self.assertEqual(native_results.pop(), ("M004", "M004-S01", ()))
        self.assertEqual(len(observations), len(_PROFILE_VARIANTS))

    def test_pinned_profile_valid_native_invalid_prompt_stays_native_invalid(self) -> None:
        pinned = _FIXTURES / "profile_valid_native_invalid_prompt.md"
        observation = observe_okf_profile_path(pinned)
        self.assertEqual(_layers(observation), ("pass", None, "pass", None))
        self.assertEqual(observation.execution_eligibility, "not_evaluated")
        meta = _meta_text(pinned.read_text(encoding="utf-8"))
        self.assertFalse(meta.valid)
        self.assertEqual(meta.milestone_id, "")
        self.assertEqual(meta.slice_id, "")
        self.assertIn("could not parse milestone_id from coding prompt", meta.errors)


class ReportAndVerdictMutationTests(unittest.TestCase):
    _REPORT_BODY = "# Review\n\n## Verdict\n\npass\n"

    def test_profile_variants_never_move_review_verdict_parsing(self) -> None:
        verdicts = set()
        for label, frame in _PROFILE_VARIANTS.items():
            with self.subTest(variant=label):
                text = frame.format(kind="review_report") + self._REPORT_BODY
                result = parse_review_report_verdict_text(text)
                verdicts.add((result.verdict, result.raw_verdict, tuple(result.errors)))
        self.assertEqual(len(verdicts), 1)

    def test_blocked_verdict_is_equally_unaffected(self) -> None:
        body = "# Review\n\n## Verdict\n\nblocked\n"
        results = {
            parse_review_report_verdict_text(frame.format(kind="review_report") + body).verdict
            for frame in _PROFILE_VARIANTS.values()
        }
        self.assertEqual(len(results), 1)


def _project_with_variant(root: Path, frame_template: str) -> None:
    """One accepted slice (M001-S01), live frontier at M001-S02; every
    artifact carries the variant's concept frontmatter above identical
    native content."""

    def frame(kind: str) -> str:
        return frame_template.format(kind=kind)

    _make_template(root)
    _write_active_roadmap(root, "### M001: Test\n\nStatus: active\n\n")
    _write_detailed_roadmap(
        root,
        "### M001: Test\n\nSlices:\n- M001-S01: first slice\n- M001-S02: second slice\n\n",
    )
    _write_coding_prompt(
        root,
        "001_first_slice.md",
        frame("coding_prompt") + _minimal_coding_prompt(1),
    )
    _write_self_report(
        root,
        "05_governance/reviews/m001_s01_first_slice_self_report.md",
        frame("self_report") + _minimal_self_report(),
    )
    _write_review_prompt(root, "001_review_something.md")
    (root / "05_governance" / "reviews" / "m001_s01_review_report.md").write_text(
        frame("review_report") + "# Review\n\n## Verdict\n\npass\n", encoding="utf-8"
    )
    (root / "05_governance" / "reviews" / "m001_s01_verdict_record.md").write_text(
        frame("verdict_record")
        + "# Verdict Record\n\n## Source\n\n"
        + "Review report: `05_governance/reviews/m001_s01_review_report.md`\n",
        encoding="utf-8",
    )


def _normalized_cli_state(root: Path) -> dict[str, str]:
    state: dict[str, str] = {}
    for verb in ("status", "next", "orchestrator-plan"):
        for extra in ((), ("--json",)):
            code, out, err = _run([verb, str(root), *extra])
            key = verb + ("+json" if extra else "")
            normalized = out.replace(str(root), "<ROOT>").replace(
                str(root).replace("\\", "\\\\"), "<ROOT>"
            ).replace(str(root).replace("\\", "/"), "<ROOT>")
            state[key] = f"rc={code}\n{normalized}\nerr={err}"
    return state


class ProjectAuthorityMutationTests(unittest.TestCase):
    """The same project under five profile variants yields identical native
    state: acceptance, frontier, gate, actor, journal, handoffs, and the
    bytes a mutating command writes."""

    def test_profile_variants_change_no_native_project_state(self) -> None:
        states: dict[str, dict[str, str]] = {}
        handoffs: dict[str, tuple[str, str]] = {}
        generated: dict[str, bytes] = {}
        for label, frame_template in _PROFILE_VARIANTS.items():
            with tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp) / "proj"
                root.mkdir()
                _project_with_variant(root, frame_template)
                states[label] = _normalized_cli_state(root)
                coder = build_coder_handoff(root).content.replace(str(root), "<ROOT>")
                reviewer = build_reviewer_handoff(root).content.replace(
                    str(root), "<ROOT>"
                )
                handoffs[label] = (coder, reviewer)
                self.assertFalse((root / JOURNAL_REL_PATH).exists())
                # A mutating command still writes, and writes the same bytes.
                code, out, err = _run(["make-coding-prompt", str(root)])
                self.assertEqual(code, 0, (out, err))
                written = sorted(
                    (root / "prompts" / "for_coding_agent").glob("002_*.md")
                )
                self.assertEqual(len(written), 1)
                generated[label] = written[0].read_bytes()
                self.assertFalse((root / JOURNAL_REL_PATH).exists())
        baseline = states["legacy"]
        for label, state in states.items():
            with self.subTest(surface="cli", variant=label):
                self.assertEqual(state, baseline)
        for label, pair in handoffs.items():
            with self.subTest(surface="handoff", variant=label):
                self.assertEqual(pair, handoffs["legacy"])
        for label, content in generated.items():
            with self.subTest(surface="generated", variant=label):
                self.assertEqual(content, generated["legacy"])

    def test_observing_every_artifact_changes_no_state_or_byte(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "proj"
            root.mkdir()
            _project_with_variant(root, _PROFILE_VARIANTS["profile_valid"])
            before_cli = _normalized_cli_state(root)
            snapshot = {
                path.relative_to(root).as_posix(): (
                    path.read_bytes(),
                    path.stat().st_mtime_ns,
                )
                for path in sorted(root.rglob("*"))
                if path.is_file()
            }
            for path in sorted(root.rglob("*.md")):
                observe_okf_profile_path(path)
            after = {
                path.relative_to(root).as_posix(): (
                    path.read_bytes(),
                    path.stat().st_mtime_ns,
                )
                for path in sorted(root.rglob("*"))
                if path.is_file()
            }
            self.assertEqual(snapshot, after)
            self.assertFalse((root / JOURNAL_REL_PATH).exists())
            self.assertEqual(_normalized_cli_state(root), before_cli)

    def test_native_paths_never_call_the_observation_even_when_it_raises(self) -> None:
        # Patch the observation to raise (and, in turn, to every result class):
        # no native surface may reach it, so nothing changes and nothing raises.
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "proj"
            root.mkdir()
            _project_with_variant(root, _PROFILE_VARIANTS["profile_valid"])
            baseline = _normalized_cli_state(root)
            handoff = build_coder_handoff(root).content
            with mock.patch.object(
                frutlups.okf_profile,
                "observe_okf_profile_path",
                side_effect=AssertionError("a native path called the observation"),
            ), mock.patch.object(
                frutlups,
                "observe_okf_profile_path",
                side_effect=AssertionError("a native path called the observation"),
            ):
                self.assertEqual(_normalized_cli_state(root), baseline)
                self.assertEqual(build_coder_handoff(root).content, handoff)
                self.assertEqual(build_reviewer_handoff(root).content,
                                 build_reviewer_handoff(root).content)

    def test_status_json_carries_no_observation_key(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "proj"
            root.mkdir()
            _project_with_variant(root, _PROFILE_VARIANTS["profile_valid"])
            _, out, _ = _run(["status", str(root), "--json"])
            payload = json.dumps(json.loads(out)).lower()
            for token in ("okf", "observe", "profile_observation", "framework_profile"):
                self.assertNotIn(token, payload)


if __name__ == "__main__":
    unittest.main()
